# Build stage
FROM golang:alpine


RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.9/main' >> /etc/apk/repositories

RUN apk update && \
    apk upgrade && \
    apk add gcc \
    libc-dev \
    git \
    pkgconfig


ENV GO111MODULE=on

COPY . /go/src/github.com/thirdeye-labs/go-onvif
WORKDIR /go/src/github.com/thirdeye-labs/go-onvif/cmd/discover
RUN go build -o go-onvif

WORKDIR /app/go-onvif
RUN cp -a /go/src/github.com/thirdeye-labs/go-onvif/cmd/discover/. /app/go-onvif


ENTRYPOINT ["/app/go-onvif/go-onvif"]
